import type { MenuItem } from "@/lib/types";

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "burger-classic",
    name: "Classic Burger",
    description: "Beef patty, cheese, lettuce, special sauce",
    price: 14900,
    category: "Snacks",
    emoji: "🍔",
    isAvailable: true,
  },
  {
    id: "burger-chicken",
    name: "Chicken Burger",
    description: "Crispy chicken, mayo, pickles",
    price: 12900,
    category: "Snacks",
    emoji: "🍗",
    isAvailable: true,
  },
  {
    id: "fries",
    name: "French Fries",
    description: "Crispy salted fries",
    price: 7900,
    category: "Snacks",
    emoji: "🍟",
    isAvailable: true,
  },
  {
    id: "samosa",
    name: "Samosa (2 pcs)",
    description: "Hot and crispy potato samosas",
    price: 4900,
    category: "Snacks",
    emoji: "🥟",
    isAvailable: true,
  },
  {
    id: "nachos",
    name: "Loaded Nachos",
    description: "Cheese, salsa, jalapeños",
    price: 9900,
    category: "Snacks",
    emoji: "🧀",
    isAvailable: false,
  },
  {
    id: "cola",
    name: "Cola",
    description: "Chilled 330ml can",
    price: 4000,
    category: "Drinks",
    emoji: "🥤",
    isAvailable: true,
  },
  {
    id: "lime-soda",
    name: "Lime Soda",
    description: "Fresh lime, soda, a pinch of salt",
    price: 4500,
    category: "Drinks",
    emoji: "🍋",
    isAvailable: true,
  },
  {
    id: "coffee",
    name: "Hot Coffee",
    description: "Strong cafe-style coffee",
    price: 6000,
    category: "Drinks",
    emoji: "☕",
    isAvailable: true,
  },
  {
    id: "brownie",
    name: "Chocolate Brownie",
    description: "Warm brownie with chocolate sauce",
    price: 8900,
    category: "Desserts",
    emoji: "🍫",
    isAvailable: true,
  },
];
